### ISSUE TITLE
Feature request: UDP support in Load Balancers

### ISSUE THREAD

**Issue by bergkvist** [digitalocean/DOKS#30]
I want to use Wireguard (VPN) to create a persistent connection between a Kubernetes cluster and a server hosted elsewhere.

Wireguard uses UDP for communication, but UDP is not supported in the DigitalOcean load balancers. A NodePort Service is not ideal because Node IPs are not static, and will change when the nodes are recycled (like during a Kubernetes version upgrade). I want to use a LoadBalancer because this gives me a static IP.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: wireguard-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: wireguard
  ports:
  - port: 51820
    targetPort: wireguard-port
    protocol: UDP
```
