### ISSUE TITLE
Cronjob TimeZone in >=1.27, TZ not found

### ISSUE THREAD

**Issue by kirinnee** [digitalocean/DOKS#32]
when trying to apply the `timeZone` field for Kubernetes `cronjob` kind:
```
CronJob.batch "helium-scheduler" is invalid: spec.timeZone: Invalid value: "Asia/Singapore": unknown time zone Asia/Singapore
```
Where can I check the supported timezone or if this feature is available?

**Comment by timoreimann** [comment]
👋 

According to [the documentation of the `CronJobSpec` section](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec), all time zones from [this Wikipedia page](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) should work, which [includes Asia/Singapore](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#SINGAPORE).

I just extended [the documented CronJob example](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#example) by the `timeZone` field as following:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  timeZone: Asia/Singapore
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

It applies correctly for me:

```shell
$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6

$ kubectl apply -f cj.yaml
cronjob.batch/hello created
```

Are you using the correct API version `batch/v1`? If so, could you please share the relevant portions of your CronJob manifest?
